### ISSUE TITLE
Vue 3 support + Composition API

### ISSUE THREAD

**Issue by oleksii-shaposhnikov** [pixari/vue-i18n-extract#104]
Does the current version of the extracted plugin support Vue 3 and composition API?

Will it work with "vue-i18n": "^9.0.0-rc.4" ?

**Comment by pixari** [comment]
I am pretty sure it will work, even if I didn't test it.
The vuei18n keys syntax hasn't changed, that's why it should just work fine.

**Comment by andreasphil** [comment]
Hi @pixari,

I just set up `vue-i18n-extract` with `"vue-i18n": "^9.0.0-beta.0"`. We're using `vue-i18n` with the Composition API as described [here](https://vue-i18n.intlify.dev/guide/advanced/composition.html#basic-usage):

```js
setup(props, { emit }) {
  const { t } = useI18n();
  // ...
  
  return { t }
```

And then in the template:

```vue
<q-expansion-item expand-separator dense :label="t('dialog.infos')"></q-expansion-item>
```

The tool will report `dialog.infos` as unused because the regex used in [`vue-files.ts`](https://github.com/pixari/vue-i18n-extract/blob/master/src/report-command/vue-files.ts) doesn't match if there's no space, $ or dot in front of the `t`. If I change the variable name in `setup` to `const { t: $t }` it works fine.

Is that intended behavior? I'd prefer to stick with `const { t }` as that's what the official docs say and it comes more natural.

An easy fix would be to update the regex such that it also matches on `"t` or maybe even `:propname="t`. What do you think?

I'd be happy to contribute if you agree.

Thanks for your work!

**Comment by JkmAS** [comment]
I have the same issue as @andreasphil mentioned https://github.com/pixari/vue-i18n-extract/issues/104#issuecomment-873110239

![issue-regex](https://user-images.githubusercontent.com/9950469/130447776-ba99e0f6-eed2-4f92-913a-bb5dba297960.png)


> If I change the variable name in setup to const { t: $t } it works fine.

And I tried the solution with renaming `t -> $t`, but it didn't work for me on development env:

`setup() return property "$t" should not start with "$" or "_" which are reserved prefixes for Vue internals.`

@pixari could you pls reopen this issue and check this out. Thx

**Comment by Spittal** [comment]
Hey guys! I added full vue 3 and vue-i18n v9 support here, I'm using this branch internally and it works great. https://github.com/pixari/vue-i18n-extract/pull/124

Just waiting for @pixari to review.

**Comment by JkmAS** [comment]
@Spittal  first thank you for v2.0 :clap:, I've already migrated and everything works smoothly.
But unfortunately it didn't solve the problem with `t('key')` if I pass it to component's props.

There is a problem in the [first regex group](https://github.com/pixari/vue-i18n-extract/blob/master/src/create-report/vue-files.ts#L70 ) in `[$ ?]`, because this construction is not optional. 

Regex: ```/(?:[$ .]tc?)\(\s*?(["'`])((?:[^\\]|\\.)*?)\1/g;```

My component: 

```vue
<Checkbox
  :label="t('forms.promoter.label.terms')"
  name="terms-agreement"
/>
```

Thx

**Comment by Spittal** [comment]
@JkmAS fixed this in https://github.com/pixari/vue-i18n-extract/commit/8d55c138179c110cf6e8fd4388aa4b8985ce4381

I couldn't make that group optional because it would throw some false positives, but I worked around it by adding quotes to the matching group. We'll release this fix soon!

**Comment by JkmAS** [comment]
>  but I worked around it by adding quotes to the matching group. 

@Spittal yeah, that's a better solution :clap:. Thx
