### ISSUE TITLE
Dynamic translation keys

### ISSUE THREAD

**Issue by jamiechong** [pixari/vue-i18n-extract#46]
So I'm not sure how to solve this really, but here's the problem. 

It picks this up as a `Missing i18n Entry`
`lang.label.${choice}`

And in my lang files it picks these up as `Unused i18n Entry`
```
lang.label.ar-AE
lang.label.de-DE
lang.label.en-US
lang.label.es-ES
lang.label.fr-CA
lang.label.fr-FR
lang.label.he-IL
```

My code has this within a loop where `choice` is one of  `[ar-AE, de-DE, en-US, etc]`: 
```
<label :for="choice">{{ $t(`lang.label.${choice}`) }}</label>
```

Could your tool treat the `${choice}` as a wildcard somehow and therefore not flag these items as missing?

**Comment by Spittal** [comment]
Yeah there are several occasions where you want some dynamic content in your paths. I've seen this with:

1. The `v-t` directive that allows for an object to be passed through, as opposed to a string literal.
2. A case that I patched out a while ago https://github.com/pixari/vue-i18n-extract/commit/30fb684b2a25fb1e3dcdb7ff32e165dde9e26e6d which allows for using a dynamic `:path` in a `<i18n>` component
3. A template literal variable like in the example the OP posted.

I've thought a lot about how we can achieve support for dynamic paths... Let me sort of 'brain dump' here and maybe someone smarter than me can chime in:

1. Recognize via the `RegExp` matchers that an `I18NItem` path is dynamic. Dynamic can mean different things (see the list above) so we need ways to know which 'type' of dynamic path we have.
2. Somehow get the component name associated with the dynamic path. This is harder than is sounds, because we can't assume the template and component script are always in the same file.
3. Once we have the component name, boot up the Vue app and find the component based on it's name. This isn't full proof because we're just assuming that the component will be in the tree, which isn't always the case...

This is where I hit a wall, there isn't some 'full proof' way to evaluate the dynamic path without making a lot of assumptions about the users source code.

So, I'm open to hearing some other solutions. Or, possible workarounds we should document to make sure users know that this is a limitation of the library.

**Comment by pixari** [comment]
I did some "experiments" in this direction but I wasn't successful.
I could boot up the Vue app but then it was very complicated to be 100% sure that I was covering all 
cases.

I have the feeling this isn't the best approach, but as you said, I'm waiting for someone smarter than me (there are a lot of them out there). :)

**Comment by LordGordonQ** [comment]
## Proposal 1
A quick workaround could be a "classic" ignore comment to tell vue-i18n-extract to ignore some entries we know are highly dynamics.

code:
```
translateOption(field, opt) {
  return opt === null || opt === '' ? '' : this.$t(`${field}.${opt}`); // vue-i18n-extract: ignore
},
```

translation:
```
export default {
  field: {
    example: 'some translation', // vue-i18n-extract: ignore
  }
}
```
---
## Proposal 2

Building on the previous example we can use the comment to "tag" the dynamic lines with the used strings, as a mapping, to avoid dangling translations in case of refactoring.

code:
```
translateOption(field, opt) {
  return opt === null || opt === '' ? '' : this.$t(`${field}.${opt}`); // vue-i18n-extract: tag=ABC
},
```

translation:
```
export default {
  field: {  // vue-i18n-extract: ABC:field
    example: 'some translation', // vue-i18n-extract: ABC:opt
  }
}
```

**Comment by pixari** [comment]
Hi @LordGordonQ,

I really like the Proposal 2.

Did you think about the implementation?

**Comment by LordGordonQ** [comment]
> Hi @LordGordonQ,
> I really like the Proposal 2.
> Did you think about the implementation?

Thanks. Not really: I haven't studied the code for this plugin. I'm just an user.

Yet, I thought that if you are able to capture the `vue-i18n-extract` in the comments then you should be able to parse the rest of the comment to look for configuration options and store them in a dictionary (or something useful) to use as support.

**Comment by Spittal** [comment]
I will take a look this weekend to implement this!

**Comment by ewohlken2** [comment]
To me, dynamic translations keys are an anti-pattern when trying to build a fully automated translation system. But I still have a few in the codebase I'm working on that I can't get rid of just yet, and they are polluting my vue-i18n-extract output.

I'd like to be able to ignore dynamic keys, either outright or with comments like in proposal 1.

Proposal 2 is interesting, but my project shares translation data with a non-js application so it would be difficult to add meta-data to the translations that only vue-i18n knows about

Good luck with whatever you decide and thank you @pixari for maintaining this tool!

**Comment by LordGordonQ** [comment]
> To me, dynamic translations keys are an anti-pattern when trying to build a fully automated translation system. But I still have a few in the codebase I'm working on that I can't get rid of just yet, and they are polluting my vue-i18n-extract output.

In my case I have lot of dynamic data coming from external API, so I cannot create full static translations at build time.

> Proposal 2 is interesting, but my project shares translation data with a non-js application so it would be difficult to add vue specific metadata to the translations

I had the same problem in a previous project, where some translation was done by VueJS and others by the back end. It's hard to maintain.

So, in this new project I designed that the back end serves data and metadata via API, but has no knowledge on the user's language. Only VueJS knows the true user's language, thus all the translation is done in VueJS. This also avoid to have translation strings scattered between the back end code and the front end code.

**Comment by HugoHeneault** [comment]
As a simpler implementation, would a simple option ignoring strings ending by `.` be sufficient? 

It would then ignore 

* `errors.`
* `locales.`

I saw someone already worked on something: https://github.com/aldarund/vue-i18n-extract/commit/7fe5fe6d28c06e95f9a6743b2a603b3abf1fc267

I will try to implement and propose a PR for that :)

**Comment by HugoHeneault** [comment]
I've implemented a simple dynamic keys handling system. You can review or check it on #74 🍻

**Comment by vmangelovv** [comment]
is there any movement on the issue?

**Comment by HugoHeneault** [comment]
@vmangelovv You can use my repo as long as it's not merged, I use it for one of my production project :)

**Comment by vmangelovv** [comment]
> @vmangelovv You can use my repo as long as it's not merged, I use it for one of my production project :)

can you give an example of ignoring dynamic key?

**Comment by HugoHeneault** [comment]
As I wrote on the #74:

* You should run with the `vue-i18n-extract` with `-d` param
* All keys containing `${` caracters or ending by a dot `.` are considered as dynamic.

**Comment by pdcmoreira** [comment]
For anyone that might be interested, I'm doing this as a workaround:

**Script in `package.json`:**
```json
{
  "scripts": {
    "i18n-report": "vue-i18n-extract report -v \"./src/components/**/{*.?(js|vue),.i18nignore}\" -l \"./src/i18n/!(index).?(js|json|yml|yaml)\""
  }
}
```

**`.i18nignore` file:**
```
$t('label_one')
$t('label_two')
$t('label_three')
$t('label_four')
```
You can add one of these per component or a global one for all components, whatever you might prefer.

This would be a cool adition to the core (by specifying just the keys, not the entire `$t('...')` mock), since it's simple and similar to other tools, like `.gitignore` or `.eslintignore`.
