### ISSUE TITLE
NPM v1.0.3 has no -a option

### ISSUE THREAD

**Issue by Hagith** [pixari/vue-i18n-extract#71]
It is strange but v1.0.3 which is available on NPM has no `-a` option.

Download package and check the code:
```
npm pack vue-i18n-extract
tar -xvvzf vue-i18n-extract-1.0.3.tgz
cat package/dist-node/index.js
```

Output:
```
...
async function report(command) {
  const {
    vueFiles,
    languageFiles,
    output
  } = command;
...
```

**Comment by Gitsack** [comment]
Ah i guess that's why the add functionality is not working?

The following lists all unused and all not yet included annotations perfectly but does not add missing keys to the translation json files (version 1.0.3):

`vue-i18n-extract report -v './src/modules/**/*.?(js|vue)' -l './src/locales/*.?(js|json)' -a true`

**Comment by Spittal** [comment]
Hello!

I've just finished up a PR  #70 to address this issue and extend the `-a` functionality to include not only `JSON` files but also `JS` and `Yaml`. It will be merged and released soon.

**Comment by o-Chamie-o** [comment]
@Spittal is there any requirement to have the -a / --add working?

I got the report, but even with the --add flag I don't have the missing string added to my json.

Here is my command (on windows (tried it as simple user and as administrator) : 
```
npx vue-cli-service i18n:report --src "./src/**/*.?(vue)" --locales "./src/locales/**/*.json" -a
```
