### ISSUE TITLE
vue-i18n-extract overwrites global `require`

### ISSUE THREAD

**Issue by rashfael** [pixari/vue-i18n-extract#79]
vue-i18n-extract overwrites the global `require` here:
https://github.com/pixari/vue-i18n-extract/blob/1591c94ae19239cbd77c3c9da0ef67f4bcfe8c1d/src/report-command/language-files.ts#L10

This causes problems with other modules.
In my case vue-i18n-extract gets loaded via vue-cli-plugin-i18n before the vue cli webpack build, which then breaks a loader down the line, because `esm` is not handling hashbangs correctly (`#!/usr/bin/env node`).

**Comment by pixari** [comment]
What do you suggest?

**Comment by Spittal** [comment]
To keep compatibility with a wide range of projects, using CJS and ESM I've rewritten the file to no longer override `require`

Fix is in this commit: https://github.com/pixari/vue-i18n-extract/commit/0d367afb0e415b2d5f1ac7cfafab6339a43f27e9

**Comment by kleinfreund** [comment]
@Spittal Not sure if that was intentional, but the files in the dist directory are no longer minified.

**Comment by Spittal** [comment]
It's because of node support in microbundle. I guess they chose that as default for `--target node` because it isn't in a browser environment where every byte over HTTP matters. I think it makes it a little easier to read and debug! :D

Also I should mention that @pixari and I talked about it. And very _very_ few people were using ESM for language files and we figured it was just easier to remove them until the Node ecosystem has wider support for native ESM handling. You can see this change reflected in master.
